// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: test-import.capnp

#include "test-import.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<31> b_bc55b08b672b5d97 = {
  {   0,   0,   0,   0,   5,   0,   5,   0,
    151,  93,  43, 103, 139, 176,  85, 188,
      0,   0,   0,   0,   1,   0,   0,   0,
    110, 198,   3,   3,  51, 123, 109, 243,
      1,   0,   6,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     17,   0,   0,   0, 234,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 101, 115, 116,  45, 105, 109, 112,
    111, 114, 116,  46,  99,  97, 112, 110,
    112,  58,  84, 101, 115, 116,  73, 109,
    112, 111, 114, 116,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   2,   0,   1,   0,
     16,   0,   0,   0,   2,   0,   1,   0,
    102, 105, 101, 108, 100,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    253,  99,  11, 184,  20, 243, 168, 160,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
static const ::capnp::_::RawSchema* const d_bc55b08b672b5d97[] = {
  &s_a0a8f314b80b63fd,
};
static const uint16_t m_bc55b08b672b5d97[] = {0};
static const uint16_t i_bc55b08b672b5d97[] = {0};
const ::capnp::_::RawSchema s_bc55b08b672b5d97 = {
  0xbc55b08b672b5d97, b_bc55b08b672b5d97.words, 31, d_bc55b08b672b5d97, m_bc55b08b672b5d97,
  1, 1, i_bc55b08b672b5d97, nullptr, nullptr
};
}  // namespace schemas
namespace _ {  // private
CAPNP_DEFINE_STRUCT(
    ::TestImport);
}  // namespace _ (private)
}  // namespace capnp
